// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Ghn_AlZqd5xiCuGnmyZ-Ox0jNyvwycw',
    appId: '1:762935714552:web:6e7693ac626f0ef6e7d10d',
    messagingSenderId: '762935714552',
    projectId: 'hronline-59dc8',
    authDomain: 'hronline-59dc8.firebaseapp.com',
    databaseURL: 'https://hronline-59dc8-default-rtdb.firebaseio.com',
    storageBucket: 'hronline-59dc8.firebasestorage.app',
    measurementId: 'G-8NP5TCXDE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuVNrRI-EnKYfArT9q56Ma-2SgZ9-oLQ',
    appId: '1:762935714552:android:78ac2ed8ccb4e6f8e7d10d',
    messagingSenderId: '762935714552',
    projectId: 'hronline-59dc8',
    databaseURL: 'https://hronline-59dc8-default-rtdb.firebaseio.com',
    storageBucket: 'hronline-59dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyDzpunMWxc7cyDiR71FX6_zI9hEzLJTg',
    appId: '1:762935714552:ios:6cb3a582144069c3e7d10d',
    messagingSenderId: '762935714552',
    projectId: 'hronline-59dc8',
    databaseURL: 'https://hronline-59dc8-default-rtdb.firebaseio.com',
    storageBucket: 'hronline-59dc8.firebasestorage.app',
    iosBundleId: 'com.example.hrOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyDzpunMWxc7cyDiR71FX6_zI9hEzLJTg',
    appId: '1:762935714552:ios:6cb3a582144069c3e7d10d',
    messagingSenderId: '762935714552',
    projectId: 'hronline-59dc8',
    databaseURL: 'https://hronline-59dc8-default-rtdb.firebaseio.com',
    storageBucket: 'hronline-59dc8.firebasestorage.app',
    iosBundleId: 'com.example.hrOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Ghn_AlZqd5xiCuGnmyZ-Ox0jNyvwycw',
    appId: '1:762935714552:web:7c33bfe08f6a50ffe7d10d',
    messagingSenderId: '762935714552',
    projectId: 'hronline-59dc8',
    authDomain: 'hronline-59dc8.firebaseapp.com',
    databaseURL: 'https://hronline-59dc8-default-rtdb.firebaseio.com',
    storageBucket: 'hronline-59dc8.firebasestorage.app',
    measurementId: 'G-R263E1T2PK',
  );
}
